collection/urls.py
from django.conf.urls import patterns, include, url
from collection import views

urlpatterns = patterns('',
                       url(r'^points/reset/', views.reset_status_collection, name='reset'),
                       url(r'^points/status/(?P<point_id>\d+)/', views.status_collection, name='status'),
                       url(r'^points/get/(?P<point_id>\d+)/', views.detail, name='detail'),
                       url(r'^map/company_on_map/(?P<company_id>\d+)/', views.company_on_map, name='company_on_map'),
                       url(r'^map/', views.points_on_map, name='map'),
                       url(r'^logo_map/', views.logo_map, name='logo_map'),
                       url(r'^points/', views.check_delay, name='points'),
                       url(r'^routes/', views.routes, name='routes'),
                       url(r'^', views.logo_map, name='index'),

)

diplom_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^', include('collection.urls', namespace="collection")),

)

collection/models.py
from django.db import models

# Create your models here.

class Company(models.Model):
    class Meta():
        db_table = "company"

    company_name = models.CharField(max_length=200)
    company_color = models.CharField(max_length=50)
    company_logo = models.CharField(max_length=50)

    def __unicode__(self):
        return self.company_name


class Point(models.Model):
    class Meta():
        db_table = "point"

    point_address = models.CharField(max_length=200)
    point_telephone = models.CharField(max_length=50, default="+7(909)-905-73-32")
    point_coordinates = models.CharField(max_length=100)
    point_time_collection = models.TimeField()
    point_delay_collection = models.TimeField(default="00:00:00")
    point_delay_color = models.CharField(max_length=50, default="black")
    point_status_collection = models.BooleanField(default=False)
    point_company = models.ForeignKey(Company)

    def __unicode__(self):
        return self.point_address


class Route(models.Model):
    class Meta():
        db_table = "route"

    route_current_position = models.CharField(max_length=100)
    route_color = models.CharField(max_length=50, default="808080")
    route_point = models.ForeignKey(Point)

    def __unicode__(self):
        return self.route_current_position


class Delay(models.Model):
    class Meta():
        db_table = "delay"

    delay_name = models.CharField(max_length=50)
    delay_max = models.TimeField(default="00:00:00")

    def __unicode__(self):
        return self.delay_name

collection/views.py
# coding=utf-8
from django.shortcuts import render_to_response, redirect
from django.http.response import Http404
from django.core.exceptions import ObjectDoesNotExist
from models import Company, Point, Route, Delay
from datetime import datetime, timedelta


def detail(request, point_id):
    return render_to_response('point.js', dict(point=Point.objects.get(id=point_id)))


def company_on_map(request, company_id):
    return render_to_response('company_on_map.js', dict(company=Company.objects.get(id=company_id),
                                                        points=Point.objects.filter(point_company=company_id)))


def points_on_map(request):
    now = datetime.now()
    null = (datetime.strptime("0:00:00", "%H:%M:%S")).time()
    delay_max = Delay.objects.get(delay_name="15 minutes").delay_max
    for point in Point.objects.all():
        tc = datetime.combine(now.date(), point.point_time_collection)
        if now > tc and point.point_status_collection == False:
            delay = (now - timedelta(hours=tc.hour, minutes=tc.minute, seconds=tc.second)).time()
        else:
            delay = null
        if delay > delay_max:
            color = "#FF0000"  # red
        else:
            color = "#008000"  # green
        point.point_delay_color = color
        point.point_delay_collection = delay
        point.save()
    return render_to_response('points_on_map.js', {'companies': Company.objects.all(),
                                                   'points': Point.objects.all()})


def logo_map(request):
    return render_to_response('logo_map.js', {'companies': Company.objects.all(),
                                              'points': Point.objects.all()})


def routes(request):
    point1 = Point.objects.get(point_address="Московская обл., Химки г., Ленинградское ш., вл. 5")
    point2 = Point.objects.get(point_address="Реутов, ул.Октября, стр.10")
    point3 = Point.objects.get(point_address="Москва, ул. Покрышкина, 4")
    return render_to_response('route.js', dict(routes=Route.objects.all(),
                                               point1=point1,
                                               point2=point2,
                                               point3=point3,
                                               companies=Company.objects.all()))


def check_delay(request):
    now = datetime.now()
    null = (datetime.strptime("0:00:00", "%H:%M:%S")).time()
    delay_max = Delay.objects.get(delay_name="15 minutes").delay_max
    for point in Point.objects.all():
        tc = datetime.combine(now.date(), point.point_time_collection)
        if now > tc and point.point_status_collection == False:
            delay = (now - timedelta(hours=tc.hour, minutes=tc.minute, seconds=tc.second)).time()
        else:
            delay = null
        if delay > delay_max:
            color = "#FF0000"  # red
        else:
            color = "#008000"  # green
        point.point_delay_color = color
        point.point_delay_collection = delay
        point.save()
    return render_to_response('points.html', dict(companies=Company.objects.all(),
                                                  points=Point.objects.all()))


def status_collection(request, point_id):
    try:
        point = Point.objects.get(id=point_id)
        point.point_status_collection = "True"
        point.save()
    except ObjectDoesNotExist:
        raise Http404
    return redirect('/points/')


def reset_status_collection(request):
    try:
        Point.objects.all().update(point_status_collection=False)
    except ObjectDoesNotExist:
        raise Http404
    return redirect('/points/')

collection/templates/points.html
{% extends 'main.html' %}

{% block points %}

<div class="container">
    <label><input type="button" value="Сброс" onclick="location.href ='{% url 'collection:reset' %}'"></label>
    <div class="row">
     {%for company in companies %}
        <div class="col-md-4">
            <h3><strong>{{	company.id }}. <a href="{% url 'collection:company_on_map' company.id %}">{{ company.company_name }}</a></strong></h3>
            {% for point in points %}
                {% if company.id == point.point_company.id %}
                    <p>
                        <img src="/static/img/{{ company.company_logo }}" height="20px", width="20px" align="left">
                        <font color="{{ company.company_color }}">
                            <h4><a href="{% url 'collection:detail' point.id %}">{{ point.point_address }}</a></h4>
                        </font>
                    </p>
                    <h4>Телефон: {{ point.point_telephone }}</h4>
                    <h5>Время инкассации: {{ point.point_time_collection }}</h5>
                    <font color="{{ point.point_delay_color }}">
                        <h5>Задержка инкассации: {{ point.point_delay_collection }}</h5>
                    </font>
                    <input type="button" value="Инкассация проведена"
                                  onclick="location.href ='{% url 'collection:status' point.id %}'">
                    {% if point.point_status_collection == False %}
                        <img src="/static/img/false.png" height="20px", width="20px" align="center">
                    {% else %}
                        <img src="/static/img/true.png" height="20px", width="20px" align="center">
                    {% endif %}
                    <hr>
                {% endif %}
            {% endfor %}
            <hr>
        </div> <!--col-md-4   -->
     {% endfor %}
    </div> <!--row   -->
</div> <!--container   -->
{% endblock %}

diplom_project/templates/main.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Django</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
    <!--<script src="{% static "js/api-maps.yandex.ru.js" %}" type="text/javascript"></script>-->
    {% block marks_map %}{% endblock %}
    {% block logo_map %}{% endblock %}
    {% block route %}{% endblock %}
    {% block point %}{% endblock %}
</head>

<body>
    <!-Меню навигации->
    <div class="navbar navbar-inverse navbar-fixed-top">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'collection:index'  %}">Главная страница</a></li>
                <li><a href="{% url 'collection:points' %}">Список объектов инкассации</a></li>
                <li><a href="{% url 'collection:map' %}">Задержка инкассации на карте</a></li>
                <!--<li><a href="{% url 'collection:logo_map' %}">Лого на карте</a></li>-->
                <li><a href="{% url 'collection:routes' %}">Маршруты инкассации</a></li>
                <a href="/admin/">Админка</a>
            </ul>
    </div>
    <div id="map"></div>
    <div class="container" style="margin-top: 50px;">
        {% block points %}{% endblock %}
    </div>


</body>
</html>